# Numpy

## Task 1

You should import the necessary libraries. You will use `numpy` and `sys` libraries.


> Don't forget to import `numpy` in the short form.

In [2]:
import sys

import numpy as np

## Task 2

Create arrays with using Python default syntax and using `numpy`. Also, print the size of the arrays in bytes. You should use `sys` library for this task.

Requirements for arrays:
* length of the array should be `1000`;
* array should contain zeros;
* the second array should be generated by `numpy` library, and should have as little memory as possible.

In [3]:
py_arr = [0] * 1000
sys.getsizeof(py_arr)

8056

In [4]:
np_arr = np.array(py_arr, dtype=np.int8)
sys.getsizeof(np_arr)

1112

## Task 3

Write manually a small float array using `numpy` syntax number should be in the range from `0` to `10.0`. Also, you should get the first, the third, and the last elements of the array using multi-indexing.

Requirements:
* length of the array should be from `5` to `10`.

In [5]:
np_arr = np.array([1, 2, 3.3, 4.1, .5], dtype=float)
np_arr[[0, 2, -1]]

array([1. , 3.3, 0.5])

## Task 4

You have the array `array = np.array([2.3, 7.8, 3.2, 1.1, 5.8, 9.5, 17.6, 11.1])` using multi-indexing you should summarize a subsequence of an array and get the `27` as the result.

In [6]:
array = np.array([2.3, 7.8, 3.2, 1.1, 5.8, 9.5, 17.6, 11.1])
array[[0, 1, 4, -1]].sum()

np.float64(27.0)

## Task 5

You have a matrix `A`:

```python
A = np.array([
    [1, 6],
    [2, 8],
    [3, 11],
    [3, 10],
    [1, 7]
])
```

Follow the comments in the next cells and write the code.

In [7]:
A = np.array([
    [1, 6],
    [2, 8],
    [3, 11],
    [3, 10],
    [1, 7]
])

### Task 5.1 Find the mean for each column by `x` axis

In [8]:
A.mean(axis=0)

array([2. , 8.4])

### Task 5.2 Get the standard deviation by `y` axis

In [9]:
A.std(axis=1)

array([2.5, 3. , 4. , 3.5, 3. ])

### Task 5.3 Get the sum of all elements in `A` by `y` axis

In [27]:
A.sum(axis=1)

array([ 7, 10, 14, 13,  8])

### Task 5.4 Get the following result using multi-dim selection:

```python
[
    [1, 6],
    [2, 8],
 ]
```

In [11]:
A[:2, :]

array([[1, 6],
       [2, 8]])

##  Task 5.5. Get the following result using multi-dim selection:
```python
[
    [1, 6],
    [3, 11],
    [1, 7]
 ]
```

In [12]:
A[::2, :]

array([[ 1,  6],
       [ 3, 11],
       [ 1,  7]])

## Task 6

Rewrite Python code to `numpy` code. Also, estimate the time of execution for both implementations.

> Please, note: `unknown_signature` this name just hide the real name of the function, to make the task more complicated.

### Task 6.1

In [13]:
# Python code
%time result = [i for i in range(1000000)] 
len(result)

CPU times: total: 31.2 ms
Wall time: 70.3 ms


1000000

In [14]:
%time result = np.arange(1000000)
result.size

CPU times: total: 15.6 ms
Wall time: 9.01 ms


1000000

### Task 6.2

In [15]:
# Python code
def unknown_signature(vector1, vector2):
    result = 0
    for i in range(len(vector1)):
        result += vector1[i] * vector2[i]
    return result

vector1 = [1, 2, 3]
vector2 = [4, 5, 6]
result = 0

%time unknown_signature(vector1, vector2)

CPU times: total: 0 ns
Wall time: 0 ns


32

In [16]:
vector1 = np.array([1, 2, 3], dtype=np.int8)
vector2 = np.array([4, 5, 6], dtype=np.int8)

%time (vector1 * vector2).sum()

CPU times: total: 0 ns
Wall time: 0 ns


np.int64(32)

### Task 6.3

In [17]:
# Python code
def unknown_signature(matrix1, matrix2):
    result = []
    for i in range(len(matrix1)):
        row = []
        for j in range(len(matrix1[i])):
            row.append(matrix1[i][j] * matrix2[i][j])
        result.append(row)
    return result

matrix1 = [[1, 2], [3, 4]]
matrix2 = [[5, 6], [7, 8]]

%time unknown_signature(matrix1, matrix2)

CPU times: total: 0 ns
Wall time: 0 ns


[[5, 12], [21, 32]]

In [18]:
matrix1 = np.array([[1, 2], [3, 4]], dtype=np.int8)
matrix2 = np.array([[5, 6], [7, 8]], dtype=np.int8)

%time matrix1 * matrix2

CPU times: total: 0 ns
Wall time: 0 ns


array([[ 5, 12],
       [21, 32]], dtype=int8)

### Task 6.4

In [19]:
# Python code
def unknown_signature(lst):
    total = 0
    for num in lst:
        total += num
    result = total / len(lst)
    return result

lst = [1, 2, 3, 4, 5]

%time unknown_signature(lst)

CPU times: total: 0 ns
Wall time: 0 ns


3.0

In [20]:
np_arr = np.array([1, 2, 3, 4, 5], dtype=np.int8)

%time np_arr.mean()

CPU times: total: 0 ns
Wall time: 0 ns


np.float64(3.0)

## Task 7

Rewrite Python code to `numpy` code (Masks).

### Task 7.1

In [21]:
# Python code
def unknown_signature(lst, mask, new_value):
    for i in range(len(lst)):
        if mask[i]:
            lst[i] = new_value

lst = [1, 2, 3, 4, 5]
mask = [True, False, True, False, True]
new_value = 0
unknown_signature(lst, mask, new_value)
lst

[0, 2, 0, 4, 0]

In [22]:
np_arr = np.array([1, 2, 3, 4, 5], dtype=np.int8)
mask = np.array([True, False, True, False, True], dtype=np.bool)
np.where(mask, 0, np_arr)

array([0, 2, 0, 4, 0], dtype=int8)

### Task 7.2

In [23]:
# Python code
def unknown_signature(lst1, lst2):
    bitwise_complement = [~x for x in lst1]
    bitwise_and = [x & y for x, y in zip(lst1, lst2)]
    bitwise_or = [x | y for x, y in zip(lst1, lst2)]
    return bitwise_complement, bitwise_and, bitwise_or

list1 = [5, 2, 7, 4, 9]
list2 = [3, 6, 1, 8, 10]
result_bitwise_complement, result_bitwise_and, result_bitwise_or = unknown_signature(list1, list2)
result_bitwise_complement, result_bitwise_and, result_bitwise_or

([-6, -3, -8, -5, -10], [1, 2, 1, 0, 8], [7, 6, 7, 12, 11])

In [24]:
np_arr1 = np.array([5, 2, 7, 4, 9], dtype=np.int8)
np_arr2 = np.array([3, 6, 1, 8, 10], dtype=np.int8)

np.bitwise_invert(np_arr1), np.bitwise_and(np_arr1, np_arr2), np.bitwise_or(np_arr1, np_arr2)

(array([ -6,  -3,  -8,  -5, -10], dtype=int8),
 array([1, 2, 1, 0, 8], dtype=int8),
 array([ 7,  6,  7, 12, 11], dtype=int8))

### Task 7.3 Optional

In [25]:
# Python code
def unknown_signature(lst):
    result = []
    for num in lst:
        if num % 2 == 0 and (num % 3 == 0 or num > 10):
            modified_num = (num ^ 7) + 2
            result.append(modified_num)
    return result

my_list = [6, 9, 12, 14, 17, 20]
result_python_style = unknown_signature(my_list)
result_python_style

[3, 13, 11, 21]

In [26]:
np_arr = np.array([6, 9, 12, 14, 17, 20], dtype=np.int8)
mask = (np_arr % 2 == 0) & ((np_arr % 3 == 0) | (np_arr > 10))
np_arr = np_arr[mask]
(np_arr ^ 7 ) + 2

array([ 3, 13, 11, 21], dtype=int8)